{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b1bacf29",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"194e7004\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"# a) Thủ tục: tham số là n, in ra tổng 1+2+...+n\\n\",\n",
    "    \"def tong_n(n):\\n\",\n",
    "    \"    S = n * (n+1) // 2\\n\",\n",
    "    \"    print(f\\\"Tổng 1+2+...+{n} = {S}\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"# b) Thủ tục: tham số m, n → kiểm tra nguyên tố cùng nhau\\n\",\n",
    "    \"def nguyen_to_cung_nhau(m, n):\\n\",\n",
    "    \"    if math.gcd(m, n) == 1:\\n\",\n",
    "    \"        print(\\\"Hai số này là nguyên tố cùng nhau\\\")\\n\",\n",
    "    \"    else:\\n\",\n",
    "    \"        print(\\\"Hai số này không là nguyên tố cùng nhau\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"# c) Thủ tục: tham số s (số giây) → đổi sang giờ, phút, giây\\n\",\n",
    "    \"def doi_giay(s):\\n\",\n",
    "    \"    h = s // 3600\\n\",\n",
    "    \"    m = (s % 3600) // 60\\n\",\n",
    "    \"    g = s % 60\\n\",\n",
    "    \"    print(f\\\"{s} giây = {h} giờ, {m} phút, {g} giây\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"# d) Thủ tục: tham số a, b → trả về |a-b|\\n\",\n",
    "    \"def tri_tuyet_doi(a, b):\\n\",\n",
    "    \"    return abs(a - b)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# ===============================\\n\",\n",
    "    \"# Demo chạy thử\\n\",\n",
    "    \"tong_n(10)                   # a)\\n\",\n",
    "    \"nguyen_to_cung_nhau(14, 25)  # b)\\n\",\n",
    "    \"doi_giay(3671)               # c)\\n\",\n",
    "    \"print(\\\"|a-b| =\\\", tri_tuyet_doi(5.7, 2.3))  # d)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"710bd281\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"# a) Tổng 1+2+...+n\\n\",\n",
    "    \"def tong_n(n: int) -> int:\\n\",\n",
    "    \"    return n * (n + 1) // 2\\n\",\n",
    "    \"\\n\",\n",
    "    \"# b) Kiểm tra nguyên tố cùng nhau\\n\",\n",
    "    \"def nguyen_to_cung_nhau(m: int, n: int) -> str:\\n\",\n",
    "    \"    return \\\"Hai số này là nguyên tố cùng nhau\\\" if math.gcd(m, n) == 1 else \\\"Hai số này không là nguyên tố cùng nhau\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"# c) Đổi giây sang giờ, phút, giây\\n\",\n",
    "    \"def doi_giay(s: int) -> tuple[int, int, int]:\\n\",\n",
    "    \"    return divmod(s, 3600)[0], divmod(s % 3600, 60)[0], s % 60\\n\",\n",
    "    \"\\n\",\n",
    "    \"# d) |a-b|\\n\",\n",
    "    \"def tri_tuyet_doi(a: float, b: float) -> float:\\n\",\n",
    "    \"    return abs(a - b)\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\",\n",
    "    \"# ==================== DEMO ====================\\n\",\n",
    "    \"n = 10\\n\",\n",
    "    \"print(\\\"a)\\\", tong_n(n))\\n\",\n",
    "    \"\\n\",\n",
    "    \"m, k = 14, 25\\n\",\n",
    "    \"print(\\\"b)\\\", nguyen_to_cung_nhau(m, k))\\n\",\n",
    "    \"\\n\",\n",
    "    \"s = 3671\\n\",\n",
    "    \"h, p, g = doi_giay(s)\\n\",\n",
    "    \"print(f\\\"c) {s} giây = {h} giờ, {p} phút, {g} giây\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"a, b = 5.7, 2.3\\n\",\n",
    "    \"print(\\\"d) |a-b| =\\\", tri_tuyet_doi(a, b))\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"0bbd256b\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"tong_n = lambda n: n*(n+1)//2\\n\",\n",
    "    \"\\n\",\n",
    "    \"nguyen_to_cung_nhau = lambda m, n: \\\"Nguyên tố cùng nhau\\\" if math.gcd(m,n)==1 else \\\"Không nguyên tố cùng nhau\\\"\\n\",\n",
    "    \"\\n\",\n",
    "    \"doi_giay = lambda s: (s//3600, (s%3600)//60, s%60)\\n\",\n",
    "    \"\\n\",\n",
    "    \"tri_tuyet_doi = lambda a,b: abs(a-b)\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(\\\"a)\\\", tong_n(10))\\n\",\n",
    "    \"print(\\\"b)\\\", nguyen_to_cung_nhau(14, 25))\\n\",\n",
    "    \"print(\\\"c)\\\", doi_giay(3671))\\n\",\n",
    "    \"print(\\\"d)\\\", tri_tuyet_doi(5.7, 2.3))\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.7\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
