{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1f7c18c9",
   "metadata": {},
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"id\": \"33525b8c\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"diện tích hình tròn là:  28.274333882308138\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"'''\\n\",\n",
    "    \" Viết chương trình Python tính diện tích hình tròn với bán kính được \\n\",\n",
    "    \"nhập từ bàn phím\\n\",\n",
    "    \"'''\\n\",\n",
    "    \"\\n\",\n",
    "    \"#cơ bản\\n\",\n",
    "    \"import math\\n\",\n",
    "    \"r = float (input (\\\"nhập vào bán kính hình tròn (r): \\\"))\\n\",\n",
    "    \"s = math.pi * r**2\\n\",\n",
    "    \"print (\\\"diện tích hình tròn là: \\\", s)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 4,\n",
    "   \"id\": \"287de48b\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Diện tích hình tròn với bán kính 3.0 là: , 28.27\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"#nâng cao\\n\",\n",
    "    \"import math\\n\",\n",
    "    \"try:\\n\",\n",
    "    \"    r = float (input (\\\"Nhập vào bán kinh hình tròn (r): \\\"))\\n\",\n",
    "    \"    if r < 0:\\n\",\n",
    "    \"        print (\\\"Bán kính khôgn được âm, vui lòng nhập lại!\\\")\\n\",\n",
    "    \"        r = float (input (\\\"Nhập vào bán kinh hình tròn (r): \\\"))\\n\",\n",
    "    \"    else:\\n\",\n",
    "    \"        s  = math.pi * r**2\\n\",\n",
    "    \"        print (f\\\"Diện tích hình tròn với bán kính {r} là: , {s:.2f}\\\")\\n\",\n",
    "    \"except ValueError:\\n\",\n",
    "    \"    print (\\\"Vui lòng nhập số hợp lệ\\\")\\n\",\n",
    "    \"        \"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 8,\n",
    "   \"id\": \"492b6672\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Vui lòng nhập số hợp lệ và bán kính không được âm\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"#tối ưu\\n\",\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"def tinh_dien_tich_hinh_tron():\\n\",\n",
    "    \"    if r < 0:\\n\",\n",
    "    \"        raise ValueError(\\\"Bán kính không được âm\\\")\\n\",\n",
    "    \"    return math.pi * r**2\\n\",\n",
    "    \"\\n\",\n",
    "    \"try:\\n\",\n",
    "    \"    r = float (input (\\\"Nhập vào bán kinh hình tròn (r): \\\"))\\n\",\n",
    "    \"    dien_tich = tinh_dien_tich_hinh_tron()\\n\",\n",
    "    \"    print (f\\\"Diện tích hình tròn với bán kính {r} là: , {dien_tich:.2f}\\\")\\n\",\n",
    "    \"except ValueError:\\n\",\n",
    "    \"    print (\\\"Vui lòng nhập số hợp lệ và bán kính không được âm\\\")\\n\",\n",
    "    \"\\n\",\n",
    "    \"\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"b0eb34b1\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": []\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.13.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
