{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "416d074e",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"id\": \"75510501\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"S = 15\\n\",\n",
    "      \"S1 = 25\\n\",\n",
    "      \"S2 = 30\\n\",\n",
    "      \"S3 = 55\\n\",\n",
    "      \"S4 = 2.283333333333333\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"'''\\n\",\n",
    "    \"Viết chương trình tính: \\n\",\n",
    "    \" S = 1 + 2 + ... + n \\n\",\n",
    "    \" S1 = 1 + 3 + ... + (2n - 1) \\n\",\n",
    "    \" S2 = 2 + 4 + ... + 2n \\n\",\n",
    "    \" S3 = 12 + 22 + ... + n2 \\n\",\n",
    "    \" S4 = 1/1 + 1/2 + ... + 1/n \\n\",\n",
    "    \"với n nguyên dương được nhập từ bàn phím. '''\\n\",\n",
    "    \"\\n\",\n",
    "    \"n = int(input(\\\"Nhập số nguyên dương n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"# S = 1 + 2 + ... + n\\n\",\n",
    "    \"S = 0\\n\",\n",
    "    \"for i in range(1, n+1):\\n\",\n",
    "    \"    S += i\\n\",\n",
    "    \"\\n\",\n",
    "    \"# S1 = 1 + 3 + 5 + ... + (2n-1)\\n\",\n",
    "    \"S1 = 0\\n\",\n",
    "    \"for i in range(1, 2*n, 2):\\n\",\n",
    "    \"    S1 += i\\n\",\n",
    "    \"\\n\",\n",
    "    \"# S2 = 2 + 4 + ... + 2n\\n\",\n",
    "    \"S2 = 0\\n\",\n",
    "    \"for i in range(2, 2*n+1, 2):\\n\",\n",
    "    \"    S2 += i\\n\",\n",
    "    \"\\n\",\n",
    "    \"# S3 = 1^2 + 2^2 + ... + n^2\\n\",\n",
    "    \"S3 = 0\\n\",\n",
    "    \"for i in range(1, n+1):\\n\",\n",
    "    \"    S3 += i**2\\n\",\n",
    "    \"\\n\",\n",
    "    \"# S4 = 1/1 + 1/2 + ... + 1/n\\n\",\n",
    "    \"S4 = 0\\n\",\n",
    "    \"for i in range(1, n+1):\\n\",\n",
    "    \"    S4 += 1/i\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(\\\"S =\\\", S)\\n\",\n",
    "    \"print(\\\"S1 =\\\", S1)\\n\",\n",
    "    \"print(\\\"S2 =\\\", S2)\\n\",\n",
    "    \"print(\\\"S3 =\\\", S3)\\n\",\n",
    "    \"print(\\\"S4 =\\\", S4)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"91086df4\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"S  = 21\\n\",\n",
    "      \"S1 = 36\\n\",\n",
    "      \"S2 = 42\\n\",\n",
    "      \"S3 = 91\\n\",\n",
    "      \"S4 = 2.45\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"#nâng cao\\n\",\n",
    "    \"n = int(input(\\\"Nhập số nguyên dương n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"S  = n*(n+1)//2\\n\",\n",
    "    \"S1 = n**2\\n\",\n",
    "    \"S2 = n*(n+1)\\n\",\n",
    "    \"S3 = n*(n+1)*(2*n+1)//6\\n\",\n",
    "    \"S4 = sum(1/i for i in range(1, n+1))\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(\\\"S  =\\\", S)\\n\",\n",
    "    \"print(\\\"S1 =\\\", S1)\\n\",\n",
    "    \"print(\\\"S2 =\\\", S2)\\n\",\n",
    "    \"print(\\\"S3 =\\\", S3)\\n\",\n",
    "    \"print(\\\"S4 =\\\", S4)\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
