{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "47f003a3",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 2,\n",
    "   \"id\": \"924adb72\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"6\\n\",\n",
    "      \"Bạn về nhà vào: Chủ nhật\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"start = \\\"Thứ Tư\\\"\\n\",\n",
    "    \"nights = 137\\n\",\n",
    "    \"\\n\",\n",
    "    \"thu = [\\\"Thứ Hai\\\", \\\"Thứ Ba\\\", \\\"Thứ Tư\\\", \\\"Thứ Năm\\\", \\\"Thứ Sáu\\\", \\\"Thứ Bảy\\\", \\\"Chủ nhật\\\"]\\n\",\n",
    "    \"idx_start = thu.index(start)\\n\",\n",
    "    \"idx_end = (idx_start + nights) % 7   # 137 đêm ~ 137 ngày\\n\",\n",
    "    \"print(idx_end)\\n\",\n",
    "    \"print(\\\"Bạn về nhà vào:\\\", thu[idx_end])  # -> Chủ nhật\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"b6b07d5f\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"def ngay_ve_nha(start_day: str, nights: int) -> str:\\n\",\n",
    "    \"    thu = [\\\"Thứ Hai\\\", \\\"Thứ Ba\\\", \\\"Thứ Tư\\\", \\\"Thứ Năm\\\", \\\"Thứ Sáu\\\", \\\"Thứ Bảy\\\", \\\"Chủ nhật\\\"]\\n\",\n",
    "    \"    if start_day not in thu:\\n\",\n",
    "    \"        return \\\"Ngày bắt đầu không hợp lệ\\\"\\n\",\n",
    "    \"    return thu[(thu.index(start_day) + nights) % 7]\\n\",\n",
    "    \"\\n\",\n",
    "    \"start = input(\\\"Nhập ngày bắt đầu (Thứ Hai ... Chủ nhật): \\\").strip()\\n\",\n",
    "    \"nights = int(input(\\\"Nhập số đêm đã ở: \\\"))\\n\",\n",
    "    \"print(\\\"Bạn về nhà vào:\\\", ngay_ve_nha(start, nights))\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.7\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
