{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0941e6b5",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"id\": \"45d1d524\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"2 x 1 = 2\\n\",\n",
    "      \"2 x 2 = 4\\n\",\n",
    "      \"2 x 3 = 6\\n\",\n",
    "      \"2 x 4 = 8\\n\",\n",
    "      \"2 x 5 = 10\\n\",\n",
    "      \"2 x 6 = 12\\n\",\n",
    "      \"2 x 7 = 14\\n\",\n",
    "      \"2 x 8 = 16\\n\",\n",
    "      \"2 x 9 = 18\\n\",\n",
    "      \"2 x 10 = 20\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"n = int(input(\\\"Nhập số nguyên (1 < n < 9): \\\"))\\n\",\n",
    "    \"if 1 < n < 9:\\n\",\n",
    "    \"    for i in range(1, 11):\\n\",\n",
    "    \"        print (f\\\"{n} x {i} = {n * i}\\\")\\n\",\n",
    "    \"else:\\n\",\n",
    "    \"    print(\\\"Số không hợp lệ\\\")\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 3,\n",
    "   \"id\": \"ddb3f6c0\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Bảng cửu chương của 5:\\n\",\n",
    "      \" 5 x  1 =  5\\n\",\n",
    "      \" 5 x  2 = 10\\n\",\n",
    "      \" 5 x  3 = 15\\n\",\n",
    "      \" 5 x  4 = 20\\n\",\n",
    "      \" 5 x  5 = 25\\n\",\n",
    "      \" 5 x  6 = 30\\n\",\n",
    "      \" 5 x  7 = 35\\n\",\n",
    "      \" 5 x  8 = 40\\n\",\n",
    "      \" 5 x  9 = 45\\n\",\n",
    "      \" 5 x 10 = 50\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"def BCC (n):\\n\",\n",
    "    \"    if not (1 < n < 9):\\n\",\n",
    "    \"        return f\\\"lỗi: n = {n} không hợp lệ chỉ từ 2 đến 8\\\"\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    print(f\\\"Bảng cửu chương của {n}:\\\")\\n\",\n",
    "    \"    for i in range(1, 11):\\n\",\n",
    "    \"        print (f\\\"{n:2} x {i:2} = {n * i:2}\\\")\\n\",\n",
    "    \"        \\n\",\n",
    "    \"try:\\n\",\n",
    "    \"    n = int(input(\\\"Nhập số nguyên (1 < n < 9): \\\"))\\n\",\n",
    "    \"    BCC(n)\\n\",\n",
    "    \"except ValueError:\\n\",\n",
    "    \"    print(\\\"Lỗi: Vui lòng nhập số nguyên hợp lệ\\\")\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
