{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d6b5c9a",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 10,\n",
    "   \"id\": \"ed53f2b7\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Số nhị phân là:  101\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"n = int(input('Nhap n: '))\\n\",\n",
    "    \"print(\\\"Số nhị phân là: \\\", bin(n)[2:])\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 11,\n",
    "   \"id\": \"d129d536\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Số nhị phân là: 11\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"n = int(input('Nhập vào n:'))\\n\",\n",
    "    \"if n == 0:\\n\",\n",
    "    \"    print(\\\"Số nhị phân là: 0\\\")\\n\",\n",
    "    \"else:\\n\",\n",
    "    \"    binary = ''\\n\",\n",
    "    \"    m = n\\n\",\n",
    "    \"    while m > 0:\\n\",\n",
    "    \"        binary = str(m % 2) + binary\\n\",\n",
    "    \"        m = m // 2\\n\",\n",
    "    \"    print(\\\"Số nhị phân là:\\\", binary)\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"be2c03ae\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"#dùng đệ quy\\n\",\n",
    "    \"def dec_to_bin(n):\\n\",\n",
    "    \"    if n == 0:\\n\",\n",
    "    \"        return ''\\n\",\n",
    "    \"    else:\\n\",\n",
    "    \"        return dec_to_bin(n // 2) + str(n % 2)\\n\",\n",
    "    \"\\n\",\n",
    "    \"n = int(input('Nhập vào n: '))\\n\",\n",
    "    \"print(\\\"Số nhị phân là:\\\", dec_to_bin(n) if n != 0 else '0')\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
