{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d01eeaf8",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"c1507b06\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"n = int(input(\\\"Nhập n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"# a) Đếm số ước nguyên tố khác nhau\\n\",\n",
    "    \"def is_prime(x):\\n\",\n",
    "    \"    if x < 2: return False\\n\",\n",
    "    \"    for i in range(2, int(x**0.5) + 1):\\n\",\n",
    "    \"        if x % i == 0: return False\\n\",\n",
    "    \"    return True\\n\",\n",
    "    \"\\n\",\n",
    "    \"dem = 0\\n\",\n",
    "    \"for i in range(1, n+1):\\n\",\n",
    "    \"    if n % i == 0 and is_prime(i):\\n\",\n",
    "    \"        dem += 1\\n\",\n",
    "    \"\\n\",\n",
    "    \"# b) Tổng các ước thực sự của n\\n\",\n",
    "    \"tong_uoc = 0\\n\",\n",
    "    \"for i in range(1, n):\\n\",\n",
    "    \"    if n % i == 0:\\n\",\n",
    "    \"        tong_uoc += i\\n\",\n",
    "    \"\\n\",\n",
    "    \"# c) Tổng bình phương 1^2 + 2^2 + ... + n^2\\n\",\n",
    "    \"tong_bp = 0\\n\",\n",
    "    \"for i in range(1, n+1):\\n\",\n",
    "    \"    tong_bp += i*i\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(\\\"a) Số ước nguyên tố khác nhau =\\\", dem)\\n\",\n",
    "    \"print(\\\"b) Tổng các ước thực sự =\\\", tong_uoc)\\n\",\n",
    "    \"print(\\\"c) Tổng bình phương =\\\", tong_bp)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"87e6788a\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"n = int(input(\\\"Nhập n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"def is_prime(x):\\n\",\n",
    "    \"    if x < 2: return False\\n\",\n",
    "    \"    for i in range(2, int(x**0.5)+1):\\n\",\n",
    "    \"        if x % i == 0: return False\\n\",\n",
    "    \"    return True\\n\",\n",
    "    \"\\n\",\n",
    "    \"# a) số ước nguyên tố khác nhau\\n\",\n",
    "    \"dem = len({i for i in range(2, n+1) if n % i == 0 and is_prime(i)})\\n\",\n",
    "    \"\\n\",\n",
    "    \"# b) tổng ước thực sự\\n\",\n",
    "    \"tong_uoc = sum(i for i in range(1, n) if n % i == 0)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# c) tổng bình phương\\n\",\n",
    "    \"tong_bp = sum(i*i for i in range(1, n+1))\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(f\\\"a) {dem}\\\\nb) {tong_uoc}\\\\nc) {tong_bp}\\\")\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"6c576136\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"n = int(input(\\\"Nhập n: \\\"))\\n\",\n",
    "    \"m = n\\n\",\n",
    "    \"prime_factors = set()\\n\",\n",
    "    \"\\n\",\n",
    "    \"# Phân tích thừa số nguyên tố\\n\",\n",
    "    \"for i in range(2, int(math.sqrt(n)) + 1):\\n\",\n",
    "    \"    if m % i == 0:\\n\",\n",
    "    \"        prime_factors.add(i)\\n\",\n",
    "    \"        while m % i == 0:\\n\",\n",
    "    \"            m //= i\\n\",\n",
    "    \"if m > 1:\\n\",\n",
    "    \"    prime_factors.add(m)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# a) Số ước nguyên tố khác nhau\\n\",\n",
    "    \"dem = len(prime_factors)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# b) Tổng ước số thực sự\\n\",\n",
    "    \"# Tính tổng tất cả ước bằng phân tích thừa số\\n\",\n",
    "    \"m = n\\n\",\n",
    "    \"sum_uoc = 1\\n\",\n",
    "    \"for p in prime_factors:\\n\",\n",
    "    \"    exp = 0\\n\",\n",
    "    \"    while m % p == 0:\\n\",\n",
    "    \"        exp += 1\\n\",\n",
    "    \"        m //= p\\n\",\n",
    "    \"    sum_uoc *= (p**(exp+1) - 1)//(p-1)\\n\",\n",
    "    \"tong_uoc = sum_uoc - n   # bỏ n đi\\n\",\n",
    "    \"\\n\",\n",
    "    \"# c) Tổng bình phương\\n\",\n",
    "    \"tong_bp = n*(n+1)*(2*n+1)//6\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(f\\\"a) {dem}\\\\nb) {tong_uoc}\\\\nc) {tong_bp}\\\")\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"language_info\": {\n",
    "   \"name\": \"python\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
