{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "58cc3166",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"id\": \"96919701\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Tong S = 33.33333333333333\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"#1\\n\",\n",
    "    \"import math \\n\",\n",
    "    \"\\n\",\n",
    "    \"x = float(input(\\\"Nhap x: \\\"))\\n\",\n",
    "    \"n = int(input(\\\"Nhap n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"S = 0\\n\",\n",
    "    \"for i in range (1, n+1):\\n\",\n",
    "    \"    S += x**i / math.factorial(i)\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(f\\\"Tong S = {S}\\\")\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 3,\n",
    "   \"id\": \"f5bba744\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"Tong S = 33.33333333333333\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"x = float(input(\\\"Nhap x: \\\"))\\n\",\n",
    "    \"n = int(input(\\\"Nhap n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"S = 0\\n\",\n",
    "    \"giai_thua = 1\\n\",\n",
    "    \"\\n\",\n",
    "    \"for i in range (1, n+1):\\n\",\n",
    "    \"    giai_thua *= i\\n\",\n",
    "    \"    S += x**i / giai_thua\\n\",\n",
    "    \"\\n\",\n",
    "    \"print(f\\\"Tong S = {S}\\\")\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"53995fcb\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"x = float(input (\\\"nhap x: \\\"))\\n\",\n",
    "    \"n = int(input (\\\"nhap n: \\\"))\\n\",\n",
    "    \"\\n\",\n",
    "    \"s , giai_thua, luy_thua = 0, 1, 1\\n\",\n",
    "    \"\\n\",\n",
    "    \"for i in range (1, n+1):\\n\",\n",
    "    \"    giai_thua *= i\\n\",\n",
    "    \"    luy_thua *= x\\n\",\n",
    "    \"    s += luy_thua / giai_thua\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.5\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
