{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "43ad2e25",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": 1,\n",
    "   \"id\": \"8d38c556\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"3\\n\",\n",
    "      \"5\\n\",\n",
    "      \"2\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"def is_prime(x):\\n\",\n",
    "    \"    if x < 2:\\n\",\n",
    "    \"        return False\\n\",\n",
    "    \"    for i in range(2, int(x**0.5) + 1):\\n\",\n",
    "    \"        if x % i == 0:\\n\",\n",
    "    \"            return False\\n\",\n",
    "    \"    return True\\n\",\n",
    "    \"\\n\",\n",
    "    \"def f(m, n):\\n\",\n",
    "    \"    ucln = min(m, n)\\n\",\n",
    "    \"    for i in range(ucln, 1, -1): \\n\",\n",
    "    \"        if m % i == 0 and n % i == 0 and is_prime(i):\\n\",\n",
    "    \"            return i\\n\",\n",
    "    \"    return 0\\n\",\n",
    "    \"\\n\",\n",
    "    \"# đề pa thử =)))\\n\",\n",
    "    \"print(f(12, 18))  # 3\\n\",\n",
    "    \"print(f(35, 50))  # 5\\n\",\n",
    "    \"print(f(8, 20))   # 2\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"ab63e0fa\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [\n",
    "    {\n",
    "     \"name\": \"stdout\",\n",
    "     \"output_type\": \"stream\",\n",
    "     \"text\": [\n",
    "      \"3\\n\",\n",
    "      \"5\\n\",\n",
    "      \"2\\n\"\n",
    "     ]\n",
    "    }\n",
    "   ],\n",
    "   \"source\": [\n",
    "    \"#GPT - xem sau\\n\",\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"def is_prime(x):\\n\",\n",
    "    \"    if x < 2:\\n\",\n",
    "    \"        return False\\n\",\n",
    "    \"    for i in range(2, int(math.isqrt(x)) + 1):\\n\",\n",
    "    \"        if x % i == 0:\\n\",\n",
    "    \"            return False\\n\",\n",
    "    \"    return True\\n\",\n",
    "    \"\\n\",\n",
    "    \"def f(m, n):\\n\",\n",
    "    \"    g = math.gcd(m, n)\\n\",\n",
    "    \"    \\n\",\n",
    "    \"    \\n\",\n",
    "    \"    # Tìm số nguyên tố lớn nhất chia g\\n\",\n",
    "    \"    for i in range(int(math.isqrt(g)), 1, -1):\\n\",\n",
    "    \"        if g % i == 0:\\n\",\n",
    "    \"            if is_prime(g // i):\\n\",\n",
    "    \"                return g // i\\n\",\n",
    "    \"            if is_prime(i):\\n\",\n",
    "    \"                return i\\n\",\n",
    "    \"    return g if is_prime(g) else 0\\n\",\n",
    "    \"\\n\",\n",
    "    \"# Test\\n\",\n",
    "    \"print(f(12, 18))  # 3\\n\",\n",
    "    \"print(f(35, 50))  # 5\\n\",\n",
    "    \"print(f(8, 20))   # 2\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"id\": \"fa723db1\",\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import math\\n\",\n",
    "    \"\\n\",\n",
    "    \"def f(m, n):\\n\",\n",
    "    \"    g = math.gcd(m, n)\\n\",\n",
    "    \"    if g < 2:\\n\",\n",
    "    \"        return 0\\n\",\n",
    "    \"    max_prime = 0\\n\",\n",
    "    \"    d = 2\\n\",\n",
    "    \"    while d * d <= g:\\n\",\n",
    "    \"        while g % d == 0:\\n\",\n",
    "    \"            max_prime = d\\n\",\n",
    "    \"            g //= d\\n\",\n",
    "    \"        d += 1 if d == 2 else 2  # sau 2 thì chỉ duyệt số lẻ\\n\",\n",
    "    \"    if g > 1:\\n\",\n",
    "    \"        max_prime = g\\n\",\n",
    "    \"    return int(max_prime)\\n\",\n",
    "    \"\\n\",\n",
    "    \"#hong biết đúnghong nữaaaa =)))\\n\",\n",
    "    \"print(f(12, 18))  # 3\\n\",\n",
    "    \"print(f(35, 50))  # 5\\n\",\n",
    "    \"print(f(8, 20))   # 2\\n\",\n",
    "    \"print(f(17, 34))  # 17\\n\",\n",
    "    \"print(f(14, 15))  # 0\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"codemirror_mode\": {\n",
    "    \"name\": \"ipython\",\n",
    "    \"version\": 3\n",
    "   },\n",
    "   \"file_extension\": \".py\",\n",
    "   \"mimetype\": \"text/x-python\",\n",
    "   \"name\": \"python\",\n",
    "   \"nbconvert_exporter\": \"python\",\n",
    "   \"pygments_lexer\": \"ipython3\",\n",
    "   \"version\": \"3.13.7\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
